export const CANDIDATE_PROFILE_SET_DATA = "CANDIDATE_PROFILE_SET_DATA";

export const CANDIDATE_CURRENT_STATUS = "CANDIDATE_CURRENT_STATUS";

export const SET_CANDIDATE__APPLIED_JOBS = "SET_CANDIDATE__APPLIED_JOBS";

export const SET_CANDIDATE_EXPERIENCE_TYPE = "SET_CANDIDATE_EXPERIENCE_TYPE";

export const SET_CANDIDATE_DEGREE_TITLES = "SET_CANDIDATE_DEGREE_TITLES";

export const SET_CANDIDATE_INSTITUTION_TYPE = "SET_CANDIDATE_INSTITUTION_TYPE";

export const SET_CANDIDATE_ALL_ANSWERS = "SET_CANDIDATE_ALL_ANSWERS";

export const SET_CANDIDATE_JOB_VIEW_DATA = "SET_CANDIDATE_JOB_VIEW_DATA";

export const SET_CANDIDATE_JOBS = "SET_CANDIDATE_JOBS";

export const SET_CANDIDATE_CERTIFICATE_TITLES = "SET_CANDIDATE_CERTIFICATE_TITLES";

export const SET_ALL_INDUSTRIES = "SET_ALL_INDUSTRIES";

export const SET_ALL_FUNCTIONS = "SET_ALL_FUNCTIONS";
