export const CANDIDATE_PROFILE_SET_DATA = "CANDIDATE_PROFILE_SET_DATA";

export const CANDIDATE_CURRENT_STATUS = "CANDIDATE_CURRENT_STATUS";

export const SET_CANDIDATE__APPLIED_JOBS = "SET_CANDIDATE__APPLIED_JOBS";

export const SET_CANDIDATE_EXPERIENCE_TYPE = "SET_CANDIDATE_EXPERIENCE_TYPE";

export const SET_CANDIDATE_DEGREE_TITLES = "SET_CANDIDATE_DEGREE_TITLES";

export const SET_CANDIDATE_INSTITUTION_TYPE = "SET_CANDIDATE_INSTITUTION_TYPE";

export const SET_CANDIDATE_ALL_ANSWERS = "SET_CANDIDATE_ALL_ANSWERS";