export const UPDATE_TERMSANDCONDITIONS = "UPDATE_TERMSANDCONDITIONS";
export const UPDATE_EMAILOTP = "UPDATE_EMAILOTP";
export const UPDATE_PHONEOTP = "UPDATE_PHONEOTP";
export const UPDATE_LOGGEDIN = "UPDATE_LOGGEDIN";
export const UPDATE_SINGUP_DETAILS = "UPDATE_SINGUP_DETAILS";
export const UPDATE_JWT_TOKEN = "UPDATE_JWT_TOKEN";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
